// Icônes de marchands : des EMOJI (libres de droit par nature) — jamais de
// logos de marques, qui sont des marques déposées et exposeraient l'app à des
// problèmes juridiques. Dictionnaire local instantané ; l'IA complète pour
// les libellés inconnus quand elle est configurée.
import { normalizeText } from './text'

const MERCHANT_ICONS: Array<[string[], string]> = [
  [['carrefour', 'leclerc', 'lidl', 'auchan', 'intermarche', 'monoprix', 'casino', 'aldi', 'supermarche', 'super u', 'courses', 'marche'], '🛒'],
  [['boulangerie', 'boulanger patissier', 'patisserie'], '🥖'],
  [['netflix', 'disney', 'canal', 'cinema', 'cine'], '🎬'],
  [['spotify', 'deezer', 'musique'], '🎵'],
  [['apple', 'iphone', 'ipad', 'samsung', 'fnac', 'darty', 'boulanger.com'], '📱'],
  [['amazon', 'cdiscount', 'colis', 'la poste', 'chronopost', 'mondial relay'], '📦'],
  [['sncf', 'ratp', 'navigo', 'tgv', 'ouigo', 'train', 'metro', 'tram'], '🚆'],
  [['uber', 'taxi', 'blablacar', 'bolt'], '🚕'],
  [['essence', 'total', 'esso', 'shell', 'bp ', 'carburant', 'station'], '⛽'],
  [['parking', 'peage', 'autoroute', 'vinci'], '🅿️'],
  [['edf', 'engie', 'electricite', 'totalenergies'], '⚡'],
  [['veolia', 'suez', 'eau '], '💧'],
  [['orange', 'sfr', 'bouygues telecom', 'free mobile', 'freebox', 'internet', 'mobile'], '📶'],
  [['mcdo', 'mcdonald', 'mcdonalds', 'burger king', 'kfc', 'quick', 'kebab', 'pizza', 'sushi', 'restaurant', 'resto', 'brasserie', 'cafe', 'bistrot'], '🍽️'],
  [['pharmacie', 'medecin', 'docteur', 'dentiste', 'mutuelle', 'hopital'], '💊'],
  [['loyer', 'agence immo', 'syndic'], '🏠'],
  [['assurance', 'maif', 'macif', 'axa', 'matmut', 'gmf'], '🛡️'],
  [['salle de sport', 'basic fit', 'fitness', 'piscine', 'club '], '🏋️'],
  [['ecole', 'cantine', 'creche', 'garderie', 'etudes'], '🎒'],
  [['vetement', 'zara', 'kiabi', 'decathlon', 'h&m', 'hm '], '👕'],
  [['coiffeur', 'barbier', 'institut'], '💇'],
  [['salaire', 'paie', 'virement employeur'], '💼'],
  [['caf ', 'allocations', 'impots', 'dgfip', 'urssaf'], '🏛️'],
  [['banque', 'frais bancaires', 'agios'], '🏦'],
  [['cadeau', 'anniversaire', 'noel'], '🎁'],
  [['vacances', 'hotel', 'airbnb', 'booking', 'camping', 'vol ', 'avion'], '🏖️'],
]

/** Vrai si le mot-clé apparaît en MOTS ENTIERS dans le libellé normalisé
 * (« train » ne doit pas matcher « Trained Manager »). */
const matchesWholeWords = (normalizedPadded: string, keyword: string): boolean =>
  normalizedPadded.includes(` ${keyword.trim()} `)

/** Emoji du marchand déduit du libellé, ou null si inconnu. */
export const suggestMerchantIcon = (label: string): string | null => {
  const normalized = ` ${normalizeText(label)} `
  for (const [keywords, icon] of MERCHANT_ICONS) {
    if (keywords.some((keyword) => matchesWholeWords(normalized, keyword))) {
      return icon
    }
  }
  return null
}

/** Valide un emoji d'icône (1 à 4 unités de code, pas de texte). */
export const isValidTxIcon = (value: unknown): value is string =>
  typeof value === 'string' && value.length > 0 && value.length <= 8 && !/[a-z0-9]/i.test(value)

// ── Logos officiels (favicons) ──────────────────────────────────────────────
// Usage « nominatif » : le favicon du site officiel identifie le marchand
// d'une dépense (pratique standard des apps de budget). Jamais de logo
// embarqué dans l'app — l'icône est servie par le service favicon de Google.
// Repli : emoji suggestMerchantIcon si le marchand n'est pas reconnu ou si
// l'image ne charge pas.

const MERCHANT_DOMAINS: Array<[keywords: string[], domain: string]> = [
  [['canal plus', 'canalplus', 'mycanal', ' canal '], 'canalplus.com'],
  [['netflix'], 'netflix.com'],
  [['spotify'], 'spotify.com'],
  [['deezer'], 'deezer.com'],
  [['disney'], 'disneyplus.com'],
  [['prime video', 'amazon prime'], 'primevideo.com'],
  [['amazon'], 'amazon.fr'],
  [[' apple ', 'itunes', 'icloud'], 'apple.com'],
  [['google', 'youtube'], 'google.com'],
  [['carrefour'], 'carrefour.fr'],
  [['leclerc'], 'e.leclerc'],
  [['auchan'], 'auchan.fr'],
  [['lidl'], 'lidl.fr'],
  [['intermarche'], 'intermarche.com'],
  [['monoprix'], 'monoprix.fr'],
  [['picard'], 'picard.fr'],
  [['hellofresh', 'hello fresh'], 'hellofresh.fr'],
  [['uber eats', 'ubereats'], 'ubereats.com'],
  [[' uber '], 'uber.com'],
  [['deliveroo'], 'deliveroo.fr'],
  [['mcdo', 'mcdonald', 'mcdonalds'], 'mcdonalds.fr'],
  [['burger king'], 'burgerking.fr'],
  [['sncf', 'ouigo', 'tgv'], 'sncf-connect.com'],
  [['ratp', 'navigo'], 'ratp.fr'],
  [['blablacar'], 'blablacar.fr'],
  [[' edf '], 'edf.fr'],
  [['engie'], 'engie.fr'],
  [['totalenergies', 'total energies'], 'totalenergies.fr'],
  [['veolia'], 'veolia.fr'],
  [[' orange '], 'orange.fr'],
  [['sfr'], 'sfr.fr'],
  [['bouygues'], 'bouyguestelecom.fr'],
  [['free mobile', 'freebox', 'free '], 'free.fr'],
  [['ikea'], 'ikea.com'],
  [['leroy merlin'], 'leroymerlin.fr'],
  [['castorama'], 'castorama.fr'],
  [['decathlon'], 'decathlon.fr'],
  [['fnac'], 'fnac.com'],
  [['darty'], 'darty.com'],
  [[' boulanger '], 'boulanger.com'],
  [['zara'], 'zara.com'],
  [['kiabi'], 'kiabi.com'],
  [['h&m', 'hm '], 'hm.com'],
  [['sephora'], 'sephora.fr'],
  [['basic fit', 'basic-fit'], 'basic-fit.com'],
  [['airbnb'], 'airbnb.fr'],
  [['booking'], 'booking.com'],
  [['maif'], 'maif.fr'],
  [['macif'], 'macif.fr'],
  [[' axa '], 'axa.fr'],
  [['matmut'], 'matmut.fr'],
  [['caf ', 'allocations familiales'], 'caf.fr'],
  [['impots', 'dgfip'], 'impots.gouv.fr'],
  [['la poste'], 'laposte.fr'],
  [['doctolib'], 'doctolib.fr'],
  [['rakuten'], 'rakuten.com'],
  [['viki'], 'viki.com'],
  [['steam'], 'steampowered.com'],
  [['playstation'], 'playstation.com'],
  [['nintendo'], 'nintendo.fr'],
  // Télécom
  [['sosh'], 'sosh.fr'],
  [['red by sfr', 'red sfr'], 'red-by-sfr.fr'],
  [['b&you', 'b and you', 'bandyou'], 'bouyguestelecom.fr'],
  [['la poste mobile'], 'lapostemobile.fr'],
  [['prixtel'], 'prixtel.com'],
  [['nrj mobile'], 'nrjmobile.fr'],
  [['coriolis'], 'coriolis.com'],
  [['lebara'], 'lebara.fr'],
  [['lyca', 'lycamobile'], 'lycamobile.fr'],
  // Énergie
  [['ohm energie', 'ohm'], 'ohm-energie.com'],
  [['ekwateur'], 'ekwateur.fr'],
  [['mint energie'], 'mint-energie.com'],
  [['vattenfall'], 'vattenfall.fr'],
  [['ilek'], 'ilek.fr'],
  [['primeo', 'primeo energie'], 'primeo-energie.fr'],
  [['eni '], 'eni.com'],
  [['alterna'], 'alterna-energie.fr'],
  [['suez'], 'suez.fr'],
  [['saur'], 'saur.com'],
  // Banques et paiement
  [['boursorama', 'boursobank'], 'boursobank.com'],
  [['credit agricole', 'ca '], 'credit-agricole.fr'],
  [['bnp', 'bnp paribas'], 'bnpparibas.com'],
  [['societe generale', 'sg '], 'societegenerale.fr'],
  [['lcl'], 'lcl.fr'],
  [['caisse d epargne', 'caisse epargne'], 'caisse-epargne.fr'],
  [['banque populaire'], 'banquepopulaire.fr'],
  [['credit mutuel'], 'creditmutuel.fr'],
  [['cic'], 'cic.fr'],
  [['banque postale'], 'labanquepostale.fr'],
  [['revolut'], 'revolut.com'],
  [['n26'], 'n26.com'],
  [['lydia'], 'lydia-app.com'],
  [['paypal'], 'paypal.com'],
  [['qonto'], 'qonto.com'],
  [['fortuneo'], 'fortuneo.fr'],
  [['hello bank'], 'hellobank.fr'],
  [['monabanq'], 'monabanq.com'],
  [['shine'], 'shine.fr'],
  [['wise'], 'wise.com'],
  [['klarna'], 'klarna.com'],
  [['alma'], 'getalma.eu'],
  // Assurance et santé
  [['alan'], 'alan.com'],
  [['allianz'], 'allianz.fr'],
  [['generali'], 'generali.fr'],
  [['groupama'], 'groupama.fr'],
  [['mma'], 'mma.fr'],
  [['gmf'], 'gmf.fr'],
  [['april'], 'april.fr'],
  [['harmonie mutuelle'], 'harmonie-mutuelle.fr'],
  [['malakoff'], 'malakoffhumanis.com'],
  [['luko'], 'luko.eu'],
  [['leocare'], 'leocare.eu'],
  [['ameli', 'cpam', 'securite sociale'], 'ameli.fr'],
  [['urssaf'], 'urssaf.fr'],
  [['france travail', 'pole emploi'], 'francetravail.fr'],
  // Streaming, jeux, abonnements
  [['apple tv'], 'tv.apple.com'],
  [['paramount'], 'paramountplus.com'],
  [['ocs'], 'ocs.fr'],
  [['molotov'], 'molotov.tv'],
  [['twitch'], 'twitch.tv'],
  [['crunchyroll'], 'crunchyroll.com'],
  [['xbox', 'game pass'], 'xbox.com'],
  [['microsoft', 'office 365', 'microsoft 365'], 'microsoft.com'],
  [['adobe'], 'adobe.com'],
  [['dropbox'], 'dropbox.com'],
  [['chatgpt', 'openai'], 'openai.com'],
  [['claude', 'anthropic'], 'anthropic.com'],
  [['notion'], 'notion.so'],
  [['canva'], 'canva.com'],
  [['audible'], 'audible.fr'],
  [['kindle'], 'amazon.fr'],
  // Courses et magasins
  [['franprix'], 'franprix.fr'],
  [['naturalia'], 'naturalia.fr'],
  [['biocoop'], 'biocoop.fr'],
  [['grand frais'], 'grandfrais.com'],
  [['super u', 'hyper u', 'u express', 'magasins u'], 'magasins-u.com'],
  [['aldi'], 'aldi.fr'],
  [['costco'], 'costco.fr'],
  [['action'], 'action.com'],
  [['gifi'], 'gifi.fr'],
  [['primark'], 'primark.com'],
  [['uniqlo'], 'uniqlo.com'],
  [['c&a', 'c and a'], 'c-and-a.com'],
  [['celio'], 'celio.com'],
  [['jules'], 'jules.com'],
  [['la halle'], 'lahalle.com'],
  [['etam'], 'etam.com'],
  [['zalando'], 'zalando.fr'],
  [['vinted'], 'vinted.fr'],
  [['leboncoin', 'le bon coin'], 'leboncoin.fr'],
  [['shein'], 'shein.com'],
  [['temu'], 'temu.com'],
  [['aliexpress'], 'aliexpress.com'],
  [['cultura'], 'cultura.com'],
  [['micromania'], 'micromania.fr'],
  [['nature et decouvertes', 'nature & decouvertes'], 'natureetdecouvertes.com'],
  [['jardiland'], 'jardiland.com'],
  [['truffaut'], 'truffaut.com'],
  [['maisons du monde'], 'maisonsdumonde.com'],
  [['but '], 'but.fr'],
  [['conforama'], 'conforama.fr'],
  [['alinea'], 'alinea.com'],
  [['bricomarche'], 'bricomarche.com'],
  [['brico depot'], 'bricodepot.fr'],
  [['mr bricolage'], 'mr-bricolage.fr'],
  [['weldom'], 'weldom.fr'],
  [['okaidi'], 'okaidi.fr'],
  [['vertbaudet'], 'vertbaudet.fr'],
  [['petit bateau'], 'petit-bateau.fr'],
  [['go sport'], 'go-sport.com'],
  [['intersport'], 'intersport.fr'],
  [['nike'], 'nike.com'],
  [['adidas'], 'adidas.fr'],
  [['yves rocher'], 'yves-rocher.fr'],
  [['nocibe'], 'nocibe.fr'],
  [['marionnaud'], 'marionnaud.fr'],
  [['kiko'], 'kikocosmetics.com'],
  [['maxi zoo'], 'maxizoo.fr'],
  [['zooplus'], 'zooplus.fr'],
  [['animalis'], 'animalis.com'],
  // Restauration et livraison
  [['just eat'], 'just-eat.fr'],
  [['frichti'], 'frichti.co'],
  [['subway'], 'subway.com'],
  [['dominos', 'domino s'], 'dominos.fr'],
  [['pizza hut'], 'pizzahut.fr'],
  [['starbucks'], 'starbucks.fr'],
  [['paul '], 'paul.fr'],
  [['brioche doree'], 'briochedoree.fr'],
  [['flunch'], 'flunch.fr'],
  [['buffalo grill'], 'buffalo-grill.fr'],
  [['hippopotamus'], 'hippopotamus.fr'],
  [['courtepaille'], 'courtepaille.com'],
  [['o tacos'], 'o-tacos.com'],
  [['five guys'], 'fiveguys.fr'],
  [['popeyes'], 'popeyes.fr'],
  [['kfc'], 'kfc.fr'],
  [['quick'], 'quick.fr'],
  [['columbus cafe'], 'columbuscafe.com'],
  [['big mamma'], 'bigmammagroup.com'],
  // Transport et mobilité
  [['flixbus'], 'flixbus.fr'],
  [['trainline'], 'thetrainline.com'],
  [['lime'], 'li.me'],
  [['heetch'], 'heetch.com'],
  [['bolt'], 'bolt.eu'],
  [['getaround'], 'getaround.com'],
  [['tisseo'], 'tisseo.fr'],
  [['tcl'], 'tcl.fr'],
  [['ilevia'], 'ilevia.fr'],
  [['tbm'], 'infotbm.com'],
  [['rtm'], 'rtm.fr'],
  [['transdev'], 'transdev.com'],
  [['keolis'], 'keolis.com'],
  [['vinci autoroutes', 'vinci'], 'vinci-autoroutes.com'],
  [['sanef'], 'sanef.com'],
  [['aprr'], 'aprr.fr'],
  [['ulys'], 'ulys.com'],
  [['bip&go', 'bipandgo'], 'bipandgo.com'],
  [['indigo'], 'indigoneo.fr'],
  [['q-park', 'qpark'], 'q-park.fr'],
  [['effia'], 'effia.com'],
  [['esso'], 'esso.fr'],
  [['shell'], 'shell.fr'],
  [['bp '], 'bp.com'],
  [['avia'], 'avia-france.fr'],
  [['norauto'], 'norauto.fr'],
  [['feu vert'], 'feuvert.fr'],
  [['midas'], 'midas.fr'],
  [['speedy'], 'speedy.fr'],
  [['air france'], 'airfrance.fr'],
  [['easyjet'], 'easyjet.com'],
  [['transavia'], 'transavia.com'],
  [['ryanair'], 'ryanair.com'],
  [['vueling'], 'vueling.com'],
  [['lufthansa'], 'lufthansa.com'],
  // Loisirs et sport
  [['ugc'], 'ugc.fr'],
  [['pathe', 'gaumont'], 'pathe.fr'],
  [['cgr'], 'cgrcinemas.fr'],
  [['kinepolis'], 'kinepolis.fr'],
  [['mk2'], 'mk2.com'],
  [['fitness park'], 'fitnesspark.fr'],
  [['keep cool', 'keepcool'], 'keepcool.fr'],
  [['neoness'], 'neoness.fr'],
  [['on air'], 'onair-fitness.fr'],
  [['orange bleue'], 'lorangebleue.fr'],
  [['disneyland'], 'disneylandparis.com'],
  [['parc asterix'], 'parcasterix.fr'],
  [['fnac spectacles', 'ticketmaster'], 'ticketmaster.fr'],
  // Enfants, école, santé
  [['doctolib'], 'doctolib.fr'],
  [['pharmacie'], 'ordre.pharmacien.fr'],
  [['crous'], 'lescrous.fr'],
  // Voyages
  [['abritel', 'vrbo'], 'abritel.fr'],
  [['gites de france'], 'gites-de-france.com'],
  [['pierre et vacances', 'pierre & vacances'], 'pierreetvacances.com'],
  [['center parcs'], 'centerparcs.fr'],
  [['ibis', 'accor', 'novotel', 'mercure'], 'all.accor.com'],
  [['b&b hotel', 'b&b hotels'], 'hotel-bb.com'],
  // Divers
  [['la redoute'], 'laredoute.fr'],
  [['3 suisses'], '3suisses.fr'],
  [['interflora'], 'interflora.fr'],
  [['photobox'], 'photobox.fr'],
  [['cheerz'], 'cheerz.com'],
  [['wonderbox'], 'wonderbox.fr'],
  [['smartbox'], 'smartbox.com'],
  [['ants'], 'ants.gouv.fr'],
  [['amende', 'antai'], 'antai.gouv.fr'],
  [['tresor public', 'dgfip'], 'impots.gouv.fr'],
  [['msa'], 'msa.fr'],
]

/** Domaine officiel du marchand déduit du libellé, ou null si inconnu. */
export const suggestMerchantDomain = (label: string): string | null => {
  const normalized = ` ${normalizeText(label)} `
  for (const [keywords, domain] of MERCHANT_DOMAINS) {
    if (keywords.some((keyword) => matchesWholeWords(normalized, keyword))) {
      return domain
    }
  }
  return null
}

/** URL du favicon (64 px) servie par Google (hôte final gstatic, sans
 * redirection — la CSP img-src autorise https://*.gstatic.com). */
export const merchantFaviconUrl = (domain: string): string =>
  `https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://${encodeURIComponent(domain)}&size=64`
